package system;

import java.util.ArrayList;

import model.GameObject;

import org.lwjgl.input.Controller;
import org.lwjgl.input.Controllers;
import org.newdawn.slick.Input;
import org.newdawn.slick.SlickException;
import org.newdawn.slick.util.Log;


public class ControlManager
{
	// / CLASS NAMESPACE VARIABLES
	private static ControlManager instance = null;
	
	/// CONSTANTS
	private final static int AXISINDEX = 4;
	private final static int GREENBUTTON = 5;
	private final static int REDBUTTON = 6;
	private final static int BLUEBUTTON = 4;
	private final static int POWERBUTTON = 7;


	// / CLASS NAMESPACE FUNCTIONS
	public static void createInstance(Input init_input)
	{
		instance = new ControlManager(init_input);
	}
	
	public static ControlManager getInstance()
	{
		if(instance == null)
			System.out.println("ControlManager has not neen initialised!");
		return instance;
	}

	// / ATTRIBUTES
	public enum Device 
	{
		PS3_TURNTABLE, XBOX_TURNTABLE, KEYBOARD;
	}
	private Device device = Device.KEYBOARD;
	private Input input;
	
	// ------- input state --------
	private int wheel_direction = 0;
	private boolean any_key = false;
	// -------		-------
	
	private int deviceIndex = -1;
	private String deviceName;
	private ArrayList<Controller> controllers;

	/// METHODS
	
	// creation
	public ControlManager(Input init_input)
	{
		// Initialize variables
		input = init_input;
		controllers = new ArrayList<Controller>();
		checkDevice();
		
		
		//Controllers test
		try
		{
			input.initControllers();
			//TODO : do it better
			//Check if turntable is connected :
			for (int i=0;i<controllers.size();i++)
				if(((Controller) controllers.get(i)).getName().compareTo("Guitar Hero5 for PlayStation (R) 3") == 0) 
					System.out.println("Turntable connected.");
					
					//Get the number of axis
					//System.out.println("Number of axis : "+container.getInput().getAxisCount(2)); //4
		}
		catch (SlickException e)
		{
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
	
	// query
	
	public boolean isAnyKey()
	{
		return any_key;
	}
	
	public boolean isColourKey(ColourCode key_colour)
	{
		// No memory - it's ALWAYS the first time (?)
		input.clearControlPressedRecord();
		
		
		switch(device)
		{
			case KEYBOARD:
				switch(key_colour)
				{
					/// NB -- QWERTY vs AZERTY
					case BLUE: return input.isKeyDown(Input.KEY_W)
										|| input.isKeyDown(Input.KEY_Z);
					case RED: return input.isKeyDown(Input.KEY_X);
					case GREEN: return input.isKeyDown(Input.KEY_C);
					default: return false;
				} // switch(key_colour)
				
			case PS3_TURNTABLE:
			case XBOX_TURNTABLE:
				switch(key_colour)
				{
					case BLUE: 
						return input.isControlPressed(BLUEBUTTON, deviceIndex);
					case RED: 
						return input.isControlPressed(REDBUTTON, deviceIndex);
					case GREEN: 
						return input.isControlPressed(GREENBUTTON, deviceIndex);
					default:
						return false;
				}	// switch(key_colour)
			default:
				return false;
		}	// switch(device)
	}
	
	public int getSnakeDelta(ColourCode snake_colour)
	{
		// if snake colour key is not pressed the snake is not controlled!
		if(!isColourKey(snake_colour))
			return 0;
		
		//return wheel_direction;
		switch(device)
		{
			case PS3_TURNTABLE :
				if(input.getAxisValue(2, 0) < 0)
					return -1;
				else if(input.getAxisValue(2, 0) > 0)
					return 1;
				else
					return 0;
			
			case XBOX_TURNTABLE:
			case KEYBOARD:
			default :
				if(input.isKeyDown(Input.KEY_UP) 
						|| input.isKeyDown(Input.KEY_LEFT))
					return -1;
				else if(input.isKeyDown(Input.KEY_DOWN) 
						|| input.isKeyDown(Input.KEY_RIGHT))
					return 1;
				else
					return 0;
		}
	}
	
	/******** EVENTS *******/

	public void wheelEvent(int delta)
	{
		// Event generated by Game instance
		wheel_direction = (int) Math.signum(delta);	
	}
	
	public void anyKeyEvent()
	{
		any_key = true;
	}
	
	public void forgetEvents()
	{
		// Forget the mouse wheel direction the update after it occurs
		wheel_direction = 0;
		any_key = false;
	}
	
	/****************<********/
	
	
	///////////////////////////
	/*** DEVICE MANAGEMENT ***/
	///////////////////////////
	
	//Check if the player play with a turntable or a keyboard
	private void checkDevice()
	{
		String tamp;
		controllers = new ArrayList<Controller>();
		for (int i = 0; i < Controllers.getControllerCount(); i++) 
		{
			Controller controller = Controllers.getController(i);
			if ((controller.getButtonCount() >= 3) && (controller.getButtonCount() < 20))
			{
				controllers.add(controller);
			}
		}
		for (int i=0;i<controllers.size();i++)
		{
			tamp = ((Controller) controllers.get(i)).getName();
			if (tamp.compareTo("Guitar Hero5 for PlayStation (R) 3") == 0) 
			{
				deviceName = "Guitar Hero5 for PlayStation (R) 3";
				deviceIndex = ((Controller) controllers.get(i)).getIndex();
				device = Device.PS3_TURNTABLE;
			}
			//TODO : find the good string for the xbox device
//			if(tamp.compareTo("Guitar Hero5 for Xbox360 ??? (R) 3") == 0)
//			{
//				deviceName = "Guitar Hero5 for Xbox360 ??? (R) 3";
//				deviceIndex = ((Controller) controllers.get(i)).getIndex();	
//				device = Device.XBOXTurntable;
//			}
				
		}
	}

	public int getDeviceIndex() {
		return deviceIndex;
	}

	public Device getDevice() {
		return device;
	}

	
	
	

}
